sudo: false
language: rust
rust:
- nightly

before_script:
- pip install 'travis-cargo<0.2' --user

script:
- cargo build --verbose
- cargo build --release
- cargo build --no-default-features
- cargo test --no-default-features
- cargo test

after_success:
- travis-cargo doc-upload
