sudo: false
language: rust
rust:
- nightly
- beta
- stable
before_script:
- pip install 'travis-cargo<0.2' --user
script:
- cargo build --verbose
- cargo build --release
- cargo test
- travis-cargo --only stable doc --
- cargo build --no-default-features
after_success:
- travis-cargo --only stable doc-upload
before_deploy:
- cargo package --verbose
deploy:
  provider: releases
  api_key:
    secure: smnmx51GBKE4eJjaSeG5a//BgRbojkPNvFYOXRg7dLMEupmVuC/Ul7gTyqmnf5Or8Fb+Eobx1ROVMPMXKF7H8AscmTra5AfzUj0lfXPpJf4DLqVlPgkf/RI4PjmwD8eRTyB8ZeyLOrDwL3wzLnjf0mVL2u9NMVHCApjFugYMCEoy3t27HHHHywrtf2jZEmt4VPWusl7w2R5kSbHUu7EGblCV6geMc/Q7igXxjL/vJpGzfEk29G6nnvClDv6PSwR3PaPvaafr9sUDI6MHX3WOU0Wv88YhvSpHfytWHBTUFPDk+dVJC8/USkRfc0zSG/lpUW6ujOKMH24qlxijA6AZmbwjd9nEIspkpKNJYoQo7WA3NG/Z76/l/KjTfXH4US2Is4iErY9sPoNp0YVGPPtLdgeWo9bYqOzuJqE9vWmnQiuCLIcXAxkNSW6O3YTFMCViP0lTxitkknFGZwxiUF9wbF6bA954U/sxDSUr5dE/X6piXW+SGNINcP8uHmrIGA2ddL1gwbJ0fRtbtwLGEqdSUguY62yvllDxUmk78ppZool2wJawjXNW127yKvvOIXPZ6oyjLYX+g9spzQjZIWtfK3vaNunfTUANuJ6jXaQjNxoNi+vnsnwiUmkOyu+WFWd6C3wRDfU5DJaIycd/O1kCPP9KS+xA8zq22Zw2h4ruyUw=
  file: target/package/unqlite-$TRAVIS_TAG.crate
  on:
    tags: true
    all_branches: true
    repo: zitsen/unqlite.rs
    condition: $TRAVIS_RUST_VERSION = stable
after_deploy:
- cargo publish --token "$CRATESIO_TOKEN"
env:
  global:
  - secure: lx4bRC1ITUJv2WZiVQL3yvWx9uvcjzvDBGD1GHI5U1I2ycj+cSe/S7jCpN9ySGrVt6U8P+Ujzttd9seaintuuaSbPq14wqomajw4gIGXYU9U/nFX+d+jfUZnTKyvukNd+VjmoZizLtnlxSXS2n7h9/uap7ZzFCWADFwj7uDvXJNlJA5Tfko7ptTTp1ddeBj+8yc0CkXUl07I1Y9jgy/yyPNSUyt5PFab5vYx0s4Mg7PdXRsd99k8FA3NZnry1I3TP1fsjcfrNl8YICDJDc2JXan+Vs6YgeOlMLzbLG2IUOZa9pavkN+t2JcMz8a59lD3/B08FfQS2oiclR4eDUAQGKRI3n3AGkjfXkcqdMh+9uDz1sjZaUiB//vaNljUoNUI1DG/ap4fmCAJO/ztRn8veWzTxKcn8PuZNS5Hv3JN9xewwSR3aD7rrxU9rDMfCmmspPTYTDj88bOowdyvssKWCv570axPSzC5DgMOJYCeSgoo/Q+E1PCNED5Rm85PFwe5uUEzSxflqBkwkqd+M/iv4vNioQaN9wmRwJ4nl7qPxCEFEeXLIerULZ9MjtgYKwDZk7ZXwC5IT5RzVp2PybpHIkGzp0Vfm/8IviHGansZ2OI7NevRvMZ8X6kg+mBUwydWGPk+usf9t3pQYeMQhsy/XnTK+LBaESLcciWiesua1Nc=
  - secure: eCPsS4fCCr3wscQes2LF+X+1tofnwAwSiQwnmrK7j9EIehUAphqtFDEsa9pjDvTolj66ukPtXiGZURl1EOt/2frsBtPzccvrPkdQVftTmyNutLTX6gQw9GkJUR18XncCoV+hDq73OwebhOeaGsozn44Eh4N/IpY/JmfmvrY93BE5RcOa2pFhxLC5b9jqmaSEaCbQ7KymG3EiLHWQxZMNeXhokV3EuHdVzjptRxtqftdhOKvdL0V0UOgqtDig84SbVT3UFdxR5QgGSKO5DB5gDTPkrthH1JHLPYeQ9lcpbLdPoN433U7tW4bwbUauJQ3I1KTwFKSay932pDJRbRV0LY9lyjFW9HExUZdEDGUCTlp8tbHA1kWihNXrMcu/gEDv59eTAFjbfGH2gnZ4K2QfPC9nmEVPdiP8hzBrpMCEthUjyunDvMn/gFNMPbn2EyKrToTR4gaANJ/VqvdUgd3+6p5wcGHyusUnRWURXq1d32DbDQWFlm7UD4rsYG/GTqAQKC5I9nF4Zjxd/zup4ecVs1sPrueeyXyKgafMzFIsrBerIEqG7bFIgX4EdwS+X7VLrIWTe+1PvrXaXXGjfR8QNosW7l9ShBRsnrH1jERlEWD3nvtm7k+sdmsbi8KOOXgMrSnPtI6Cc+uZiUL/XhN9veG7ya6/vyWnXIW1TyKHSGc=
