[package]
name = "unqlite"
version = "0.1.0"
authors = ["Huo Linhe <huolinhe@berrygenomics.com>"]
license = "MIT"
readme  = "README.md"
homepage = "https://github.com/zitsen/unqlite.rs"
repository = "https://github.com/zitsen/unqlite.rs.git"
documentation = "http://zitsen.github.io/unqlite.rs"
description = "Rust `unqlite` library wrapper."
keywords = ["unqlite", "kv", "nosql"]

[dependencies]
libc = "0.2.4"

[dependencies.unqlite-sys]
version = "0.1.0"
path = "unqlite-sys"
