[package]
name = "unqlite"
version = "1.2.2"
authors = ["Huo Linhe <huolinhe@berrygenomics.com>"]
license = "MIT/Apache-2.0"
readme  = "README.md"
homepage = "https://github.com/zitsen/unqlite.rs"
repository = "https://github.com/zitsen/unqlite.rs.git"
documentation = "http://zitsen.github.io/unqlite.rs"
description = "Rust `unqlite` library wrapper."
keywords = ["unqlite", "kv", "nosql"]

[dependencies]
libc = "0.2"
unqlite-sys = "^1.0.0"

[dev-dependencies]
tempfile = "2.1.3"

[features]
default = ["enable-threads"]
# For thread-safe
enable-threads = [ "unqlite-sys/enable-threads" ]
# Other features
jx9-disable-builtin-func = [ "unqlite-sys/jx9-disable-builtin-func" ]
jx9-enable-math-func = [ "unqlite-sys/jx9-enable-math-func" ]
jx9-disable-disk-io = [ "unqlite-sys/jx9-disable-disk-io" ]
enable-jx9-hash-io = [ "unqlite-sys/enable-jx9-hash-io" ]
